# Generated by Django 2.1 on 2020-08-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment5', '0003_auto_20200816_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple', models.CharField(max_length=250, verbose_name="couple's Name")),
                ('image', models.ImageField(blank=True, null=True, upload_to='wedding_pictures', verbose_name="couples's name")),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(max_length=250, verbose_name="couple's Name")),
                ('video', models.FileField(blank=True, null=True, upload_to='wedding_videos', verbose_name='Upload video here')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Video_Poster', verbose_name='Video Poster')),
            ],
        ),
    ]
